from enum import Enum


class ReasonCode(str, Enum):
    RENEWABLES_COVER_DEMAND = "RENEWABLES_COVER_DEMAND"
    SOLAR_SURPLUS_CHARGING = "SOLAR_SURPLUS_CHARGING"
    PRECHARGE_FOR_FORECAST_DEFICIT = "PRECHARGE_FOR_FORECAST_DEFICIT"
    EVENING_PEAK_DISCHARGE = "EVENING_PEAK_DISCHARGE"
    SOC_AT_MINIMUM = "SOC_AT_MINIMUM"
    DIESEL_EFFICIENT_LOADING = "DIESEL_EFFICIENT_LOADING"
    DIESEL_CHARGING_BATTERY = "DIESEL_CHARGING_BATTERY"
    CURTAILMENT_BATTERY_FULL = "CURTAILMENT_BATTERY_FULL"
    NONCRITICAL_LOAD_SHED = "NONCRITICAL_LOAD_SHED"


class ForecastSource(str, Enum):
    OPEN_METEO = "OPEN_METEO"
    CACHE = "CACHE"
    SYNTHETIC = "SYNTHETIC"


class Language(str, Enum):
    en = "en"
    gu = "gu"
    hi = "hi"
